#include <TiltedCore/Stl.hpp>
#include <TiltedCore/Allocator.hpp>
#include <TiltedCore/Buffer.hpp>
#include <TiltedCore/Serialization.hpp>
#include <TiltedCore/ViewBuffer.hpp>
#include <glm/vec2.hpp>
#include <glm/vec3.hpp>
#include <catch2/catch.hpp>
#include <Messages/ClientMessageFactory.h>
#include <Messages/ServerMessageFactory.h>
#include <Messages/RequestWorldState.h>
#include <Messages/RequestWorldStateCell.h>
#include <Messages/NotifyWorldState.h>
#include <Messages/WorldStateTable.h>
#include <Messages/WorldStateReplay.h>
#include <limits>
#include "world_animation_fixture.h"

using namespace TiltedPhoques;

// Round 2 research handoff for docs/REFERENCE_RESEARCH.md (outside ownership).
// Primary source inspected online and locally at a898f469851c464d05137bb74b069dd234897643:
// https://github.com/alandtse/CommonLibSSE-NG/blob/ng/src/RE/T/TESObjectREFR.cpp
// GetSequence, PlaceObjectAtMe and SetMotionType distinguish Ni sequences,
// runtime identity, and Havok state. Adopt native lifecycle/retained handles;
// do not treat an event name or a dynamic local form ID as durable replicated state.
// include/RE/E/ExtraEnableStateParent.h and native 11739/140165560 confirm
// parent handle +0x14, flags +0x10. Resolve 17201/1402676C0 retains the REFR.
// Read its ID before release. Unresolved parents remain ineligible.
// https://github.com/alandtse/CommonLibSSE-NG/blob/ng/src/RE/B/BGSOpenCloseForm.cpp
// Adopt native open states: 1 open, 2 opening, 3 closed, 4 closing (14288/1401DA110).
// 56233/140A493D0 ignores VM/stack, but acceptance does not prove completion.
// Keep activation cache separate from live commands, baseline and snapshot.
// All hook function bodies, callers and register setup were freshly audited in
// round6/rubble_r2_engine_audit.log, generated by audit_rubble_r2.py.
// 36564/140658870 calls 53929/1409D8520 at 1406593F7 only in its paused branch.
// Replaced that gate with 21873/140342A00, void(), main-tail CALL 1406594A8.
// Reject non-main-loop callers and inactive VM; emit active/stalled diagnostics.
// Native flags 14646/1401E6480 and 14649/1401E6520 are void(REFR*,bool).
// Damage 14158/1401D36E0 is void(destructible*,REFR*,float,bool), ClearDestruction
// 14181/1401D61A0 is void(REFR*), finished setter 19513/1402DFA00 is
// void(REFR*,const char*), Set3D 19729/1402EAD30 forwards RCX/RDX/R8B.
// Native Enable/Disable 19800/1402F2840 and 19801/1402F2D70 derive child state;
// parent recursion is 20271/1403033E0. Never force a child's disabled flag.
// 19540/1402E2F00 restores a Ni final frame, but does not establish general graph
// or collider convergence. 14165/1401D4CB0 only restores BSDamageStage switches.
// This revision WITHDRAWS both speculative mutation paths, retaining unsupported
// authoritative values without false success or repeated explosions.
// 19512/1402DF840 lock events and actor OBJECT_ANIM_SYNC remain enabled.
// Hook entry copies the ID; no hook dereferences a REFR after calling native code.
// 56205/140A47370 and 56206/140A473F0 actor rejection remains a vanilla limitation;
// callback adapters 56591/140A59230 and 56605/140A5A430 confirm their ABIs.
// PlaceAtMe persistent effects, motion-type replication, general graph end states
// and replacement/dynamic destruction are NOT implemented. No universality claim.
// Helgen wall cause is unproven; paired world_reference_state watches and existing
// ref_bodies observations must identify the actual blocker and state divergence.

namespace
{
WorldState State(WorldStateKind aKind = WorldStateKind::Disabled, uint64_t aSequence = 1)
{
    WorldState state;
    state.Epoch = 17;
    state.Sequence = aSequence;
    state.Reference = GameId{3, 0xD9610};
    state.Cell = GameId{3, 0x3C};
    state.Kind = aKind;
    if (aKind == WorldStateKind::FinishedSequence)
        state.Animation = "CompletedSequence";
    if (aKind == WorldStateKind::AnimationEvent) state.Animation = "Open";
    if (aKind == WorldStateKind::AnimationSnapshot) { state.Value = 1; state.AnimationData = WorldAnimationFixture(); }
    if (aKind == WorldStateKind::DestructionHealth) { state.Value = 2; state.Scalar = 27.5f; }
    if (aKind == WorldStateKind::Lock) state.Value = 0x132;
    return state;
}
}

TEST_CASE("World state factories round trip every operation and cell request", "[encoding.world_state]")
{
    for (uint8_t kind = 0; kind < static_cast<uint8_t>(WorldStateKind::Count); ++kind)
    {
        RequestWorldState request;
        request.State = State(static_cast<WorldStateKind>(kind));
        REQUIRE(request.State.Valid());
        Buffer buffer(512);
        Buffer::Writer writer(&buffer);
        request.Serialize(writer);
        ViewBuffer view(buffer.GetWriteData(), writer.Size());
        Buffer::Reader reader(&view);
        auto decoded = ClientMessageFactory{}.Extract(reader);
        REQUIRE(decoded);
        REQUIRE(decoded->GetOpcode() == RequestWorldState::Opcode);
        REQUIRE(static_cast<RequestWorldState&>(*decoded) == request);

        NotifyWorldState notify;
        notify.LeaderId = 23;
        notify.State = request.State;
        Buffer output(512);
        Buffer::Writer out(&output);
        notify.Serialize(out);
        ViewBuffer outputView(output.GetWriteData(), out.Size());
        Buffer::Reader in(&outputView);
        auto received = ServerMessageFactory{}.Extract(in);
        REQUIRE(received);
        REQUIRE(received->GetOpcode() == NotifyWorldState::Opcode);
        REQUIRE(static_cast<NotifyWorldState&>(*received) == notify);
    }
    RequestWorldStateCell request;
    request.Epoch = 17;
    request.Cell = GameId{9, 0x123};
    Buffer buffer(64);
    Buffer::Writer writer(&buffer);
    request.Serialize(writer);
    Buffer::Reader reader(&buffer);
    auto decoded = ClientMessageFactory{}.Extract(reader);
    REQUIRE(decoded);
    REQUIRE(decoded->GetOpcode() == RequestWorldStateCell::Opcode);
    REQUIRE(static_cast<RequestWorldStateCell&>(*decoded) == request);
}

TEST_CASE("World state rejects truncated and malformed messages", "[encoding.world_state]")
{
    RequestWorldState request;
    request.State = State(WorldStateKind::FinishedSequence);
    Buffer buffer(512);
    Buffer::Writer writer(&buffer);
    request.Serialize(writer);
    for (size_t size = 0; size < writer.Size(); ++size)
    {
        ViewBuffer view(buffer.GetWriteData(), size);
        Buffer::Reader reader(&view);
        REQUIRE_FALSE(ClientMessageFactory{}.Extract(reader));
    }
    const auto valid = request.State;
    for (int mutation = 0; mutation < 8; ++mutation)
    {
        request.State = valid;
        switch (mutation)
        {
        case 0: request.State.Epoch = 0; break;
        case 1: request.State.Sequence = 0; break;
        case 2: request.State.Reference.ModId = UINT32_MAX; break;
        case 3: request.State.Reference.BaseId = 0xFF001234; break;
        case 4: request.State.Kind = WorldStateKind::Count; break;
        case 5: request.State.Animation.assign(129, 'x'); break;
        case 6: request.State.Scalar = std::numeric_limits<float>::quiet_NaN(); break;
        case 7: request.State.Animation = String("x\0y", 3); break;
        }
        REQUIRE_FALSE(request.State.Valid());
        Buffer invalid(512);
        Buffer::Writer out(&invalid);
        request.Serialize(out);
        Buffer::Reader in(&invalid);
        REQUIRE_FALSE(ClientMessageFactory{}.Extract(in));
    }
}

TEST_CASE("World latest-state table retains independent properties and replay order", "[encoding.world_state]")
{
    WorldStateTable table;
    table.SetAuthority(17, 23);
    auto disabled = State();
    REQUIRE(table.Accept(23, disabled));
    auto animation = State(WorldStateKind::FinishedSequence, 2);
    REQUIRE(table.Accept(23, animation));
    auto newDisabled = State(WorldStateKind::Disabled, 3);
    newDisabled.Value = 1;
    REQUIRE(table.Accept(23, newDisabled));
    auto otherMod = State(WorldStateKind::Disabled, 4);
    otherMod.Reference.ModId = 8;
    REQUIRE(table.Accept(23, otherMod));
    auto otherCell = State(WorldStateKind::Lock, 5);
    otherCell.Cell = GameId{3, 0x12345};
    REQUIRE(table.Accept(23, otherCell));
    const auto snapshot = table.Snapshot(disabled.Cell);
    REQUIRE(snapshot.size() == 3);
    REQUIRE(snapshot[0] == animation);
    REQUIRE(snapshot[1] == newDisabled);
    REQUIRE(snapshot[2] == otherMod);
    REQUIRE(table.Snapshot(otherCell.Cell).size() == 1);
    REQUIRE(table.Snapshot(GameId{3, 1}).empty());
}

TEST_CASE("World authority rejects follower writes and stale revisions and isolates parties", "[encoding.world_state]")
{
    WorldStateTable table, otherParty;
    table.SetAuthority(17, 23);
    otherParty.SetAuthority(17, 24);
    auto state = State();
    REQUIRE_FALSE(table.Accept(24, state));
    REQUIRE(table.Accept(23, state));
    REQUIRE_FALSE(table.Accept(23, state));
    REQUIRE(otherParty.Snapshot(state.Cell).empty());
    auto staleEpoch = State(WorldStateKind::Disabled, 2);
    staleEpoch.Epoch = 16;
    REQUIRE_FALSE(table.Accept(23, staleEpoch));
    table.SetAuthority(17, 24);
    REQUIRE(table.Snapshot(state.Cell).size() == 1);
    auto newLeader = State();
    REQUIRE_FALSE(table.Accept(23, newLeader));
    REQUIRE(table.Accept(24, newLeader));
    REQUIRE(newLeader.Sequence > state.Sequence);
    table.SetAuthority(18, 24);
    REQUIRE(table.Snapshot(state.Cell).empty());
    REQUIRE_FALSE(table.Accept(24, state));
}
TEST_CASE("World revisions are per reference and reordered independent properties survive", "[encoding.world_state]")
{
    WorldStateTable table;
    table.SetAuthority(17, 23);
    auto first = State(WorldStateKind::Disabled, 100);
    auto second = State(WorldStateKind::Disabled, 1);
    second.Reference.BaseId += 1;
    REQUIRE(table.Accept(23, first));
    REQUIRE(table.Accept(23, second));
    REQUIRE(first.Sequence == 100);
    REQUIRE(second.Sequence == 1);
    auto earlierProperty = State(WorldStateKind::Destroyed, 90);
    REQUIRE(table.Accept(23, earlierProperty));
    auto stale = State(WorldStateKind::Disabled, 99);
    REQUIRE_FALSE(table.Accept(23, stale));
    REQUIRE(table.Snapshot(first.Cell).size() == 3);
    table.SetAuthority(17, 24);
    auto nextFirst = State();
    auto nextSecond = second;
    REQUIRE(table.Accept(24, nextFirst));
    REQUIRE(table.Accept(24, nextSecond));
    REQUIRE(nextFirst.Sequence == 101);
    REQUIRE(nextSecond.Sequence == 2);
}

TEST_CASE("World cache replaces history and moves its cell index", "[encoding.world_state]")
{
    WorldStateTable table;
    table.SetAuthority(17, 23);
    for (uint64_t i = 1; i <= 1000; ++i)
    {
        auto state = State(WorldStateKind::Disabled, i);
        state.Value = static_cast<uint32_t>(i % 2);
        REQUIRE(table.Accept(23, state));
    }
    auto moved = State(WorldStateKind::Disabled, 1001);
    const auto oldCell = moved.Cell;
    moved.Cell.BaseId += 1;
    REQUIRE(table.Accept(23, moved));
    REQUIRE(table.Snapshot(oldCell).empty());
    REQUIRE(table.Snapshot(moved.Cell).size() == 1);
    REQUIRE(table.Snapshot(moved.Cell)[0].Sequence == 1001);
}

TEST_CASE("Door live versus snapshot delivery is explicit and validated", "[encoding.world_state]")
{
    for (float mode : {0.f, 1.f, 2.f, 3.f})
    {
        auto state = State(WorldStateKind::Open);
        state.Scalar = mode;
        REQUIRE(state.Valid());
        Buffer buffer(256);
        Buffer::Writer writer(&buffer);
        state.Serialize(writer);
        Buffer::Reader reader(&buffer);
        WorldState decoded;
        REQUIRE(decoded.Deserialize(reader));
        REQUIRE(decoded == state);
    }
    auto invalid = State(WorldStateKind::Open);
    invalid.Scalar = 0.5f;
    REQUIRE_FALSE(invalid.Valid());
}
TEST_CASE("Door activation and baseline cache without driving existing followers", "[encoding.world_state]")
{
    WorldStateTable table;
    table.SetAuthority(17, 23);
    for (const float mode : {0.f, 1.f, 3.f})
    {
        auto state = State(WorldStateKind::Open, static_cast<uint64_t>(mode) + 1);
        state.Value = 1;
        state.Scalar = mode;
        REQUIRE(table.Accept(23, state));
        REQUIRE(WorldStateTable::ShouldDeliverLive(state) == (mode == 0));
        auto snapshot = table.Snapshot(state.Cell);
        REQUIRE(snapshot.size() == 1);
        REQUIRE(snapshot[0] == state); // suppressing fan-out must not discard the end state
        snapshot[0].Scalar = 2; // server cell-response policy
        WorldStateReplay replay;
        REQUIRE(replay.Receive(snapshot[0]));
        auto ready = replay.Take(64);
        REQUIRE(ready.size() == 1);
        REQUIRE(ready[0].Scalar == 2);
        replay.Applied(ready[0]);
        replay.Attach(state.Reference.LogFormat());
        ready = replay.Take(64);
        REQUIRE(ready.size() == 1);
        REQUIRE(ready[0].Scalar == 2);
    }
    REQUIRE(WorldStateTable::ShouldDeliverLive(State(WorldStateKind::Lock)));
    REQUIRE(WorldStateTable::ShouldDeliverLive(State(WorldStateKind::Disabled)));
}
TEST_CASE("Absent 3D stays pending until attach and reload reapplies the end state", "[encoding.world_state]")
{
    WorldStateReplay replay;
    auto state = State(WorldStateKind::FinishedSequence);
    REQUIRE(replay.Receive(state));
    REQUIRE(replay.Take(64).size() == 1);
    // Apply cannot run with missing/disabled 3D. There is no acknowledgement.
    REQUIRE(replay.Pending() == 1);
    REQUIRE(replay.Take(64).empty()); // no whole-history engine polling
    replay.EvictOutside({});
    REQUIRE(replay.Pending() == 1); // even leaving the cell cannot discard pending state
    replay.Attach(state.Reference.LogFormat());
    auto ready = replay.Take(64);
    REQUIRE(ready.size() == 1);
    REQUIRE(ready[0] == state);
    replay.Applied(ready[0]);
    REQUIRE(replay.Pending() == 0);
    replay.Attach(state.Reference.LogFormat());
    REQUIRE(replay.Take(64).size() == 1); // no NiNode pointer or ABA comparison
}
TEST_CASE("Pending properties replace older state without reference sequence collisions", "[encoding.world_state]")
{
    WorldStateReplay replay;
    auto first = State();
    auto second = first;
    second.Reference.BaseId += 1;
    REQUIRE(replay.Receive(first));
    REQUIRE(replay.Receive(second));
    REQUIRE(replay.Pending() == 2);
    auto newer = first;
    newer.Sequence = 2; newer.Value = 1;
    REQUIRE(replay.Receive(newer));
    replay.Applied(first); // stale completion cannot erase a newer update
    REQUIRE(replay.Pending() == 2);
    REQUIRE_FALSE(replay.Receive(first));
    auto ready = replay.Take(1);
    REQUIRE(ready.size() == 1);
    REQUIRE(ready[0] == newer);
    REQUIRE(replay.Take(1).size() == 1);
    replay.Clear();
    REQUIRE(replay.Pending() == 0);
    REQUIRE(replay.Take(64).empty());
}

TEST_CASE("Ready properties are applied in sequence order within each reference", "[encoding.world_state]")
{
    WorldStateReplay replay;
    auto later = State(WorldStateKind::Disabled, 9);
    auto earlier = State(WorldStateKind::FinishedSequence, 2);
    REQUIRE(replay.Receive(later));
    REQUIRE(replay.Receive(earlier));
    const auto first = replay.Take(1);
    REQUIRE(first.size() == 1);
    REQUIRE(first[0] == earlier);
    const auto second = replay.Take(1);
    REQUIRE(second.size() == 1);
    REQUIRE(second[0] == later);
}

TEST_CASE("Transient failure retries without another attach and does not starve other refs", "[encoding.world_state]")
{
    WorldStateReplay replay;
    auto first = State();
    auto other = first; ++other.Reference.BaseId;
    REQUIRE(replay.Receive(first));
    REQUIRE(replay.Take(1, 100).size() == 1);
    REQUIRE(replay.Failed(first, 100));
    REQUIRE(replay.Take(64, 1099).empty());
    REQUIRE(replay.Receive(other));
    auto batch = replay.Take(1, 1100);
    REQUIRE(batch.size() == 1);
    REQUIRE(batch[0] == other);
    replay.Applied(other);
    batch = replay.Take(1, 1100);
    REQUIRE(batch.size() == 1);
    REQUIRE(batch[0] == first); // missing 3D became available without Set3D
    replay.Applied(first);
    REQUIRE(replay.Pending() == 0);
    REQUIRE(replay.Take(64, 99999).empty());
}

TEST_CASE("Stale failure cannot reschedule newer work and unsupported state is retained", "[encoding.world_state]")
{
    WorldStateReplay replay;
    auto old = State();
    REQUIRE(replay.Receive(old));
    REQUIRE(replay.Take(1).size() == 1);
    auto newer = old; newer.Sequence = 2;
    REQUIRE(replay.Receive(newer));
    REQUIRE_FALSE(replay.Failed(old, 0));
    REQUIRE(replay.Take(1)[0] == newer);
    REQUIRE(replay.Failed(newer, 0, true));
    REQUIRE_FALSE(replay.Failed(newer, 0, true));
    REQUIRE(replay.Take(1, UINT64_MAX).empty());
    REQUIRE(replay.Pending() == 1);
    replay.EvictOutside({});
    REQUIRE(replay.Pending() == 1);
    replay.Attach(newer.Reference.LogFormat());
    REQUIRE(replay.Take(1)[0] == newer);
    replay.Applied(newer);
    REQUIRE(replay.Pending() == 0);
}

TEST_CASE("More than one replay budget of failures progresses fairly", "[encoding.world_state]")
{
    WorldStateReplay replay;
    for (uint32_t i = 0; i < 130; ++i)
    {
        auto state = State(); state.Reference.BaseId += i;
        REQUIRE(replay.Receive(state));
    }
    auto batch = replay.Take(64, 10);
    REQUIRE(batch.size() == 64);
    for (const auto& state : batch) replay.Failed(state, 10);
    batch = replay.Take(64, 10);
    REQUIRE(batch.size() == 64);
    for (const auto& state : batch) replay.Failed(state, 10);
    batch = replay.Take(64, 10);
    REQUIRE(batch.size() == 2);
    for (const auto& state : batch) replay.Applied(state);
    REQUIRE(replay.Take(64, 1009).empty());
    REQUIRE(replay.Take(64, 1010).size() == 64);
}
