name: Playable Skyrim Together Build

on:
  workflow_dispatch:
  schedule:
    # Every Friday at 1:00 p.m. UTC
    - cron: '0 13 * * 5'
  push:
    branches:
      - main
  workflow_call:
    inputs:
      release-version:
        required: false
        type: string
        default: ''

jobs:
  build-windows:
    if: ${{ github.repository_owner == 'tiltedphoques' || github.event_name != 'schedule' }} # Disable cron runs in forks
    uses: ./.github/workflows/windows.yml
    with:
      build-mode: release
      upload-build-for-next-job: true
      release-version: ${{ inputs.release-version || '' }}
